# Advent of Code Challenges
Code by Matthew Nemesure 

## Day 1

### Part 1

To do this, count the number of times a depth measurement increases from the previous measurement. (There is no measurement before the first measurement.)

In [4]:
data = [] # Store measurements
with open('day_1_data.txt') as f:
    for i in f.readlines():
        data.append(int(i.split("\n")[0]))

In [5]:
def calc_increased(data):
    increased = 0  # Store number of increases
    for ind, item in enumerate(data):
        if ind == 0:  # Skip first index
            continue  
        if item > data[ind-1]:  # Check if increased from previous data point
            increased +=1  # Count it
    return increased

calc_increased(data)

1374

### Part 2

Your goal now is to count the number of times the sum of measurements in this sliding window increases from the previous sum. So, compare A with B, then compare B with C, then C with D, and so on. Stop when there aren't enough measurements left to create a new three-measurement sum.

In [6]:
sliding_window_data = []  # Hold all windowed sums
for ind, item in enumerate(data):  # Loop through data
    if ind <= len(data)-3:  # Stop at the 2nd to last index
        sliding_window_data.append(sum(data[ind:ind+3]))  # add sum of current index to index + 3 to list

In [7]:
calc_increased(sliding_window_data)  # Run the calc_increased function same as part 1

1418

## Day 2

### Part 1

Your horizontal position and depth both start at 0. The steps above would then modify them as follows:

    forward 5 adds 5 to your horizontal position, a total of 5.
    down 5 adds 5 to your depth, resulting in a value of 5.
    forward 8 adds 8 to your horizontal position, a total of 13.
    up 3 decreases your depth by 3, resulting in a value of 2.
    down 8 adds 8 to your depth, resulting in a value of 10.
    forward 2 adds 2 to your horizontal position, a total of 15.
    
After following these instructions, you would have a horizontal position of 15 and a depth of 10. (Multiplying these together produces 150.)

Calculate the horizontal position and depth you would have after following the planned course. What do you get if you multiply your final horizontal position by your final depth?

In [4]:
data2 = [] # Store measurements
with open('day_2_data.txt') as f:
    for i in f.readlines():
        data2.append(i.split("\n")[0])


In [8]:
class submarine:
    def __init__(self, horizontal_start = 0, vertical_start = 0):
        self.horizontal_position = horizontal_start
        self.vertical_position = vertical_start
        
    def move_sub(self, instructions):
        split_instructions = instructions.split(" ")
        
        direction = split_instructions[0]
        amount = int(split_instructions[1])
        
        if direction == 'forward':
            self.horizontal_position+=amount
        elif direction == 'backward': # Doesn't seem to be in this data
            self.horizontal_position-=amount
        elif direction == 'down':
            self.vertical_position+=amount
        elif direction == 'up':
            self.vertical_position-=amount
        
    def multiply_horizontal_vertical(self):
        return self.horizontal_position*self.vertical_position
        

In [10]:
my_sub = submarine()
for instructions in data2:
    my_sub.move_sub(instructions)
    
print(my_sub.horizontal_position)
print(my_sub.vertical_position)
print(my_sub.multiply_horizontal_vertical())


1940
861
1670340


### Part 2

In addition to horizontal position and depth, you'll also need to track a third value, aim, which also starts at 0. The commands also mean something entirely different than you first thought:

down X increases your aim by X units.
up X decreases your aim by X units.
forward X does two things:
It increases your horizontal position by X units.
It increases your depth by your aim multiplied by X.
Again note that since you're on a submarine, down and up do the opposite of what you might expect: "down" means aiming in the positive direction.

Now, the above example does something different:

    forward 5 adds 5 to your horizontal position, a total of 5. Because your aim is 0, your depth does not change.
    down 5 adds 5 to your aim, resulting in a value of 5.
    forward 8 adds 8 to your horizontal position, a total of 13. Because your aim is 5, your depth increases by 8*5=40.
    up 3 decreases your aim by 3, resulting in a value of 2.
    down 8 adds 8 to your aim, resulting in a value of 10.
    forward 2 adds 2 to your horizontal position, a total of 15. Because your aim is 10, your depth increases by 2*10=20 to a total of 60.
    After following these new instructions, you would have a horizontal position of 15 and a depth of 60. (Multiplying these produces 900.)

Using this new interpretation of the commands, calculate the horizontal position and depth you would have after following the planned course. What do you get if you multiply your final horizontal position by your final depth?

In [12]:
# Updated submarine
class new_improved_submarine:
    def __init__(self, horizontal_start = 0, vertical_start = 0, aim = 0):
        self.horizontal_position = horizontal_start
        self.vertical_position = vertical_start
        self.aim = aim
        
    def move_sub(self, instructions):
        split_instructions = instructions.split(" ")
        
        direction = split_instructions[0]
        amount = int(split_instructions[1])
        
        if direction == 'forward':
            self.horizontal_position+=amount
            self.vertical_position+=amount*self.aim
        elif direction == 'backward': # Doesn't seem to be in this data
            self.horizontal_position-=amount
        elif direction == 'down':
            self.aim+=amount
        elif direction == 'up':
            self.aim-=amount
        
    def multiply_horizontal_vertical(self):
        return self.horizontal_position*self.vertical_position

    
my_sub_improved = new_improved_submarine()
for instructions in data2:
    my_sub_improved.move_sub(instructions)
    
print(my_sub_improved.horizontal_position)
print(my_sub_improved.vertical_position)
print(my_sub_improved.multiply_horizontal_vertical())

1940
1007368
1954293920


## Day 3

### Part 1

You need to use the binary numbers in the diagnostic report to generate two new binary numbers (called the gamma rate and the epsilon rate). The power consumption can then be found by multiplying the gamma rate by the epsilon rate.

Each bit in the gamma rate can be determined by finding the most common bit in the corresponding position of all numbers in the diagnostic report. For example, given the following diagnostic report:

00100
11110
10110
10111
10101
01111
00111
11100
10000
11001
00010
01010
Considering only the first bit of each number, there are five 0 bits and seven 1 bits. Since the most common bit is 1, the first bit of the gamma rate is 1.

The most common second bit of the numbers in the diagnostic report is 0, so the second bit of the gamma rate is 0.

The most common value of the third, fourth, and fifth bits are 1, 1, and 0, respectively, and so the final three bits of the gamma rate are 110.

So, the gamma rate is the binary number 10110, or 22 in decimal.

The epsilon rate is calculated in a similar way; rather than use the most common bit, the least common bit from each position is used. So, the epsilon rate is 01001, or 9 in decimal. Multiplying the gamma rate (22) by the epsilon rate (9) produces the power consumption, 198.

Use the binary numbers in your diagnostic report to calculate the gamma rate and epsilon rate, then multiply them together. What is the power consumption of the submarine? (Be sure to represent your answer in decimal, not binary.)

In [14]:
from collections import Counter # Useful package here

In [12]:
data3 = [] # Store measurements
with open('day_3_data.txt') as f:
    for i in f.readlines():
        data3.append(i.split("\n")[0])

In [18]:
digit_list = {} # Dictionary where key is the digit index (1,2,3,4,5 etc.) and value is list of entries over data
for digit in range(len(data3[0])): # loop through each digit
    digit_list[digit] = [] # instatiate list as dict entry
    for item in data3:
        digit_list[digit].append(item[digit]) # add item to dict

In [23]:
gamma_rate = [] # store gamma values
epsilon_rate = [] # store epsilon valeus
for key in digit_list.keys(): # loop through digit keys
    common = Counter(digit_list[key]).most_common() # get most common and least common entries
    gamma_rate.append(common[0][0]) # most common entry
    epsilon_rate.append(common[-1][0]) # least common entry

In [25]:
gamma = "".join(gamma_rate)
epsilon = "".join(epsilon_rate)

answer = int(gamma,2) * int(epsilon,2)
answer

845186

### Part 2 - This is a fun one

Keep only numbers selected by the bit criteria for the type of rating value for which you are searching. Discard numbers which do not match the bit criteria.
If you only have one number left, stop; this is the rating value for which you are searching.
Otherwise, repeat the process, considering the next bit to the right.
The bit criteria depends on which type of rating value you want to find:

To find oxygen generator rating, determine the most common value (0 or 1) in the current bit position, and keep only numbers with that bit in that position. If 0 and 1 are equally common, keep values with a 1 in the position being considered.
To find CO2 scrubber rating, determine the least common value (0 or 1) in the current bit position, and keep only numbers with that bit in that position. If 0 and 1 are equally common, keep values with a 0 in the position being considered.
For example, to determine the oxygen generator rating value using the same example diagnostic report from above:

Start with all 12 numbers and consider only the first bit of each number. There are more 1 bits (7) than 0 bits (5), so keep only the 7 numbers with a 1 in the first position: 11110, 10110, 10111, 10101, 11100, 10000, and 11001.
Then, consider the second bit of the 7 remaining numbers: there are more 0 bits (4) than 1 bits (3), so keep only the 4 numbers with a 0 in the second position: 10110, 10111, 10101, and 10000.
In the third position, three of the four numbers have a 1, so keep those three: 10110, 10111, and 10101.
In the fourth position, two of the three numbers have a 1, so keep those two: 10110 and 10111.
In the fifth position, there are an equal number of 0 bits and 1 bits (one each). So, to find the oxygen generator rating, keep the number with a 1 in that position: 10111.
As there is only one number left, stop; the oxygen generator rating is 10111, or 23 in decimal.
Then, to determine the CO2 scrubber rating value from the same example above:

Start again with all 12 numbers and consider only the first bit of each number. There are fewer 0 bits (5) than 1 bits (7), so keep only the 5 numbers with a 0 in the first position: 00100, 01111, 00111, 00010, and 01010.
Then, consider the second bit of the 5 remaining numbers: there are fewer 1 bits (2) than 0 bits (3), so keep only the 2 numbers with a 1 in the second position: 01111 and 01010.
In the third position, there are an equal number of 0 bits and 1 bits (one each). So, to find the CO2 scrubber rating, keep the number with a 0 in that position: 01010.
As there is only one number left, stop; the CO2 scrubber rating is 01010, or 10 in decimal.

In [51]:
# First lets turn my code from part 1 into a function - Need to add clause to account for ties

def get_gamma_value(input_sequence):
    digit_list = {} # Dictionary where key is the digit index (1,2,3,4,5 etc.) and value is list of entries over data
    for digit in range(len(input_sequence[0])): # loop through each digit
        digit_list[digit] = [] # instatiate list as dict entry
        for item in input_sequence:
            digit_list[digit].append(item[digit]) # add item to dict
    gamma_rate = [] # store gamma values
    epsilon_rate = [] # store epsilon valeus
    for key in digit_list.keys(): # loop through digit keys
        common = Counter(digit_list[key]).most_common() # get most common and least common entries
        if common[0][1] == common[-1][1]:
            gamma_rate.append('1')
            epsilon_rate.append('0')
        else:
            gamma_rate.append(common[0][0]) # most common entry
            epsilon_rate.append(common[-1][0]) # least common entry
    gamma = "".join(gamma_rate)
    epsilon = "".join(epsilon_rate)
    return gamma, epsilon

# Now lets begin since we have a function that can grab the most common values given an input sequence

viable_codes_g = data3 # store viable codes for oxygen (gamma)
viable_codes_e = data3 # store viable codes for c02 (epsilon)
for i in range(len(viable_codes_g[0])): # loop through each index
    if len(viable_codes_g) != 1: # stop if one value left - obviously doesn't account for edge cases
        gamma_p2, epsilon_p2 = get_gamma_value(viable_codes_g) # calculate gamma with the remaining viable codes
        new_viable_codes_g = [] # store new viable codes
        for code in viable_codes_g: # loop through current viables
            if code[i] == gamma_p2[i]: # check parameter
                new_viable_codes_g.append(code) # if met, add to new viable codes
    if len(viable_codes_e) != 1: # repeat process for epsilon
        gamma_p2, epsilon_p2 = get_gamma_value(viable_codes_e)
        new_viable_codes_e = []
        for code in viable_codes_e:
            if code[i] == epsilon_p2[i]:
                new_viable_codes_e.append(code)
    viable_codes_g = new_viable_codes_g # overwrite viable codes and repeat
    viable_codes_e = new_viable_codes_e

print(viable_codes_g)
print(viable_codes_e)
print(int(viable_codes_g[0],2))
print(int(viable_codes_e[0],2))

print(int(viable_codes_g[0],2)*int(viable_codes_e[0],2))

['010110110011']
['110001101010']
1459
3178
4636702


## Day 3

### Part 1 - Getting more difficult here

After the first five numbers are drawn (7, 4, 9, 5, and 11), there are no winners, but the boards are marked as follows (shown here adjacent to each other to save space):

After the next six numbers are drawn (17, 23, 2, 0, 14, and 21), there are still no winners:

Finally, 24 is drawn:

At this point, the third board wins because it has at least one complete row or column of marked numbers (in this case, the entire top row is marked: 14 21 17 24 4).

The score of the winning board can now be calculated. Start by finding the sum of all unmarked numbers on that board; in this case, the sum is 188. Then, multiply that sum by the number that was just called when the board won, 24, to get the final score, 188 * 24 = 4512.

In [76]:
import pandas as pd
import numpy as np
bingo_commands = pd.read_csv("day_4_data.txt", sep = '\n', header = None) # get commands
bingo_commands = [int(i) for i in bingo_commands[0][0].split(",")]
print(bingo_commands)
bingo_boards = pd.read_csv("day_4_data.txt", sep = "\n", skiprows=1, header=None) # Read in just bingo boards
bingo_boards


[17, 2, 33, 86, 38, 41, 4, 34, 91, 61, 11, 81, 3, 59, 29, 71, 26, 44, 54, 89, 46, 9, 85, 62, 23, 76, 45, 24, 78, 14, 58, 48, 57, 40, 21, 49, 7, 99, 8, 56, 50, 19, 53, 55, 10, 94, 75, 68, 6, 83, 84, 88, 52, 80, 73, 74, 79, 36, 70, 28, 37, 0, 42, 98, 96, 92, 27, 90, 47, 20, 5, 77, 69, 93, 31, 30, 95, 25, 63, 65, 51, 72, 60, 16, 12, 64, 18, 13, 1, 35, 15, 66, 67, 43, 22, 87, 97, 32, 39, 82]


0
0    10 27 53 91 86
1    15 94 47 38 61
2    32 68  8 88  9
3    35 84  3  7 87
4    62 78 90 66 64
..              ...
495  62 50 34 16  8
496  75 88 84 33 29
497   2 64 31 41 86
498  94 45 76 70  3
499  39 89 66  4 24

[500 rows x 1 columns]

In [77]:
# Process the boards into separate matricies
bingo_board_list = []
for i in range(0,len(bingo_boards), 5): # loop through with window range 5
    bingo_board = bingo_boards.iloc[i:i+5,:] # get the board in unprocessed form
    bingo_board_dict = {} # store processed board
    for ind, j in enumerate(bingo_board[0]): #loop through each row in board
        bingo_board_dict[ind] = [int(num) for num in j.split(" ") if num != ""] #get individual entries
    bingo_matrix = np.matrix(pd.DataFrame(bingo_board_dict)) # create matrix
    bingo_board_list.append(bingo_matrix) # store in board list

In [78]:
bingo_board_list[0]

matrix([[10, 15, 32, 35, 62],
        [27, 94, 68, 84, 78],
        [53, 47,  8,  3, 90],
        [91, 38, 88,  7, 66],
        [86, 61,  9, 87, 64]])

In [90]:
# Next we need to create parallel boards to track scores
# What functions do we need?
# One to generate the tracker list (list of zero matricies that track the hits on each board)
# One to update the tracking board given a number and the two boards.
# One to check for a winner



def generate_tracker_list(bingo_board_list):
    bingo_tracker_list = []
    for i in range(len(bingo_board_list)):
        bingo_tracker_list.append(np.zeros((5,5)))
    return bingo_tracker_list

# Start with updating boards
def update_board(num, bingo_board, tracking_board):
    for ind, item in enumerate(bingo_board):
        if num in item:
            indexes = np.where(np.asarray(item).flatten()==num)
            # print(indexes)
            tracking_board[ind,indexes] = 1
    return tracking_board

# Check for winners in a list of tracking boards
def check_winners(tracker_list):
    winning_inds = []
    for ind, track_board in enumerate(tracker_list):
        rowsums = track_board.sum(axis=1)
        colsums = track_board.sum(axis=0)
        if 5 in np.asarray(rowsums).flatten():
            winning_inds.append(ind)
        if 5 in np.asarray(colsums).flatten():
            winning_inds.append(ind)
    return winning_inds

In [96]:
# Put it all together
bingo_tracker_list = generate_tracker_list(bingo_board_list)

for called_num in bingo_commands: # Loop bingo commands
    for ind, board in enumerate(bingo_board_list): # Loop boards
        new_tracking_board = update_board(called_num, board, bingo_tracker_list[ind]) # Update tracking board
        #print(new_tracking_board)
        bingo_tracker_list[ind] = new_tracking_board # Update tracking board in list
    #print(bingo_tracker_list)
    winning_board_ind = check_winners(bingo_tracker_list) # find a potential winning board
    if winning_board_ind != []: # if there is one - get the number and break the lop
        winning_num = called_num
        break
print(winning_board_ind, winning_num)

[22] 46


In [97]:
# now lets calculate the final score
winning_board = bingo_board_list[winning_board_ind[0]]
winning_config = bingo_tracker_list[winning_board_ind[0]]

print(winning_board)
print(winning_config)


[[73 62 45 89 49]
 [41 99 10 17 35]
 [26 58 71 29 24]
 [87  9 28 46 74]
 [95 20 39 81 32]]
[[0. 0. 0. 1. 0.]
 [1. 0. 0. 1. 0.]
 [1. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]]


In [105]:
unmarked_sum = 0
for row_ind, i in enumerate(winning_config):
    for col_ind, j in enumerate(i):
        if j == 0:
            unmarked_sum += winning_board[row_ind,col_ind]
print(f'Final answer: {unmarked_sum*winning_num}')

Final answer: 38594


### Part 2

On the other hand, it might be wise to try a different strategy: let the giant squid win.

You aren't sure how many bingo boards a giant squid could play at once, so rather than waste time counting its arms, the safe thing to do is to figure out which board will win last and choose that one. That way, no matter which boards it picks, it will win for sure.

In the above example, the second board is the last to win, which happens after 13 is eventually called and its middle column is completely marked. If you were to keep playing until this point, the second board would have a sum of unmarked numbers equal to 148 for a final score of 148 * 13 = 1924.

Figure out which board will win last. Once it wins, what would its final score be?



In [138]:
# Put it all together with some modifications 
bingo_tracker_list = generate_tracker_list(bingo_board_list)
previous_winning_board_ind = set()
for called_num in bingo_commands: # Loop bingo commands
    for ind, board in enumerate(bingo_board_list): # Loop boards
        new_tracking_board = update_board(called_num, board, bingo_tracker_list[ind]) # Update tracking board
        bingo_tracker_list[ind] = new_tracking_board # Update tracking board in list
    winning_board_ind = set(check_winners(bingo_tracker_list)) # all unique winning boards
    # when all boards have won or when the numbers run out
    if len(winning_board_ind) == len(bingo_tracker_list) or called_num == bingo_commands[-1]:
        # Get all winners from current round that didnt win last round
        main_list = list(set(winning_board_ind) - set(previous_winning_board_ind)) # get the most recent winner(s)
        break
    else:
        # if you're not done or all winners haven't been found, record the winners from the previous loop
        previous_winning_board_ind = winning_board_ind
print(main_list, winning_num)

-------------------------------------------
set()
set()
-------------------------------------------
-------------------------------------------
set()
set()
-------------------------------------------
-------------------------------------------
set()
set()
-------------------------------------------
-------------------------------------------
set()
set()
-------------------------------------------
-------------------------------------------
set()
set()
-------------------------------------------
-------------------------------------------
set()
set()
-------------------------------------------
-------------------------------------------
set()
set()
-------------------------------------------
-------------------------------------------
set()
set()
-------------------------------------------
-------------------------------------------
set()
set()
-------------------------------------------
-------------------------------------------
set()
set()
-------------------------------------------


-------------------------------------------
{1, 2, 3, 4, 5, 6, 9, 11, 15, 17, 18, 19, 20, 21, 22, 25, 26, 28, 29, 33, 40, 41, 45, 47, 49, 50, 51, 53, 56, 57, 58, 60, 61, 66, 68, 69, 70, 77, 78, 79, 81, 86, 88, 90, 91, 92, 93, 94, 95, 98, 99}
{1, 2, 3, 4, 5, 6, 9, 11, 15, 17, 18, 20, 21, 22, 25, 26, 28, 29, 33, 40, 41, 45, 47, 49, 50, 51, 53, 56, 57, 58, 60, 61, 66, 69, 70, 77, 78, 81, 86, 88, 90, 91, 92, 93, 94, 95, 98, 99}
-------------------------------------------
-------------------------------------------
{1, 2, 3, 4, 5, 6, 9, 11, 15, 17, 18, 19, 20, 21, 22, 25, 26, 28, 29, 31, 33, 40, 41, 45, 47, 49, 50, 51, 53, 55, 56, 57, 58, 60, 61, 66, 68, 69, 70, 77, 78, 79, 81, 86, 88, 90, 91, 92, 93, 94, 95, 98, 99}
{1, 2, 3, 4, 5, 6, 9, 11, 15, 17, 18, 19, 20, 21, 22, 25, 26, 28, 29, 33, 40, 41, 45, 47, 49, 50, 51, 53, 56, 57, 58, 60, 61, 66, 68, 69, 70, 77, 78, 79, 81, 86, 88, 90, 91, 92, 93, 94, 95, 98, 99}
-------------------------------------------
------------------------------------

In [139]:
# now lets calculate the final score
losing_board = bingo_board_list[main_list[0]]
losing_config = bingo_tracker_list[main_list[0]]

print(losing_board)
print(losing_config)

[[86 53 67 23  4]
 [89 82 75 63 39]
 [64 24  3 99  7]
 [69 16 33 13 73]
 [76 51 21 43 87]]
[[1. 1. 0. 1. 1.]
 [1. 0. 1. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 0.]]


In [140]:
unmarked_sum = 0
for row_ind, i in enumerate(losing_config):
    for col_ind, j in enumerate(i):
        if j == 0:
            unmarked_sum += losing_board[row_ind,col_ind]
print(f'Final answer: {unmarked_sum*winning_num}')

Final answer: 15226
